name: neighbour_good
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  cloud_firestore: ^4.4.5
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  google_fonts: ^4.0.3
  flutter:
    sdk: flutter
  jiffy: ^5.0.0
  image_picker: ^0.8.7+1
  firebase_storage: ^11.0.16
  confirm_dialog: ^1.0.1
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/blank-profile-picture-g0d85654dd_640.png
